### ISSUE TITLE
Add support for sidecar testing bicep template

### ISSUE THREAD

**Issue by DomAyre** [microsoft/confidential-aci-testing#128]
There is a repo microsoft/confidential-sidecar-containers which uses this package for its testing. It is working fine on 1.0.6 but on 1.2.2 it fails with `c-aci-testing target run tests/attestation`, here is the message

Traceback (most recent call last):
  File "/home/runner/work/confidential-sidecar-containers/confidential-sidecar-containers/tests/attestation/test.py", line 35, in test_attestation
    aci_param_set(
  File "/home/runner/.local/lib/python3.12/site-packages/c_aci_testing/tools/aci_param_set.py", line 28, in aci_param_set
    for key, value in parameters.items():
                      ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

We need to investigate the changes between 1.0.6 and 1.2.2 and figure out why it breaks, if the issue is on the usage rather than the package itself, just leave a comment of how to fix
